# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.offer_flows_api import OfferFlowsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestOfferFlowsApi(unittest.TestCase):
    """OfferFlowsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.offer_flows_api.OfferFlowsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_createofferflow(self):
        """Test case for createofferflow

        Create a new offer flow  # noqa: E501
        """
        pass

    def test_delete_position_flow(self):
        """Test case for delete_position_flow

        Delete a specific offer flow instance  # noqa: E501
        """
        pass

    def test_getofferflow(self):
        """Test case for getofferflow

        Return a specific offer flow instance.  # noqa: E501
        """
        pass

    def test_getofferflows(self):
        """Test case for getofferflows

        List multiple offer flow resources.  # noqa: E501
        """
        pass

    def test_updateofferflow(self):
        """Test case for updateofferflow

        Update a specific offer flow instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
