# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.applicant_users_api import ApplicantUsersApi  # noqa: E501
from swagger_client.rest import ApiException


class TestApplicantUsersApi(unittest.TestCase):
    """ApplicantUsersApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.applicant_users_api.ApplicantUsersApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_applicantuserforgotpassword(self):
        """Test case for applicantuserforgotpassword

        Send an email for the applicant with the link to change password.  # noqa: E501
        """
        pass

    def test_approve_applicantion_position(self):
        """Test case for approve_applicantion_position

        Approve applied position for internal jobsite an determinated applicant.  # noqa: E501
        """
        pass

    def test_check_applicant_user_credentials(self):
        """Test case for check_applicant_user_credentials

        Check applicant-user credentials  # noqa: E501
        """
        pass

    def test_check_applicant_user_credentials_0(self):
        """Test case for check_applicant_user_credentials_0

        Check applicant-user credentials  # noqa: E501
        """
        pass

    def test_check_applicant_user_credentials_1(self):
        """Test case for check_applicant_user_credentials_1

        Request magic link to access web portal  # noqa: E501
        """
        pass

    def test_find_applicant_user_by_email(self):
        """Test case for find_applicant_user_by_email

        Check if the email is already in use.  # noqa: E501
        """
        pass

    def test_get_applicant_user_applications(self):
        """Test case for get_applicant_user_applications

        Request the applications of a applicant user from a tenant.  # noqa: E501
        """
        pass

    def test_getapplicantuser(self):
        """Test case for getapplicantuser

        Return a specific applicant user instance.  # noqa: E501
        """
        pass

    def test_new_applicant_user(self):
        """Test case for new_applicant_user

        Create a new applicant user  # noqa: E501
        """
        pass

    def test_reject_applicantion_position(self):
        """Test case for reject_applicantion_position

        Reject applied position for internal jobsite an determinated applicant.  # noqa: E501
        """
        pass

    def test_resend_email_verification(self):
        """Test case for resend_email_verification

        Resend the email verification for applicantUser  # noqa: E501
        """
        pass

    def test_save_partial(self):
        """Test case for save_partial

        Save the minimum data of ApplicantUser case his not exist in database  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
