# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.publications_api import PublicationsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestPublicationsApi(unittest.TestCase):
    """PublicationsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.publications_api.PublicationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_createpublications(self):
        """Test case for createpublications

        Create a new publications  # noqa: E501
        """
        pass

    def test_finishpublications(self):
        """Test case for finishpublications

        Finish a specific publication instance.  # noqa: E501
        """
        pass

    def test_getpublications(self):
        """Test case for getpublications

        Return a specific publication instance.  # noqa: E501
        """
        pass

    def test_getpublicationsapplicants(self):
        """Test case for getpublicationsapplicants

        Load all applicants in an integration.  # noqa: E501
        """
        pass

    def test_getpublicationsapplications(self):
        """Test case for getpublicationsapplications

        Return applications from a specific publication instance.  # noqa: E501
        """
        pass

    def test_getpublicationscanpublish(self):
        """Test case for getpublicationscanpublish

        Return if a tenant can publish a specific integration.  # noqa: E501
        """
        pass

    def test_getpublicationss(self):
        """Test case for getpublicationss

        List multiple publications resources.  # noqa: E501
        """
        pass

    def test_updatepublications(self):
        """Test case for updatepublications

        Update a specific publication instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
