# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.mappings_api import MappingsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestMappingsApi(unittest.TestCase):
    """MappingsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.mappings_api.MappingsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_approvemappings(self):
        """Test case for approvemappings

        Approve an applicant to next stage.  # noqa: E501
        """
        pass

    def test_approvemappings_0(self):
        """Test case for approvemappings_0

        Approve applicants to next stage.  # noqa: E501
        """
        pass

    def test_cancelmappings(self):
        """Test case for cancelmappings

        Rollback the applicant to previews stage.  # noqa: E501
        """
        pass

    def test_createmappingsreferral(self):
        """Test case for createmappingsreferral

        Create a new mapping based on a referral from an employee  # noqa: E501
        """
        pass

    def test_deletemappings(self):
        """Test case for deletemappings

        Delete a specific mappings  # noqa: E501
        """
        pass

    def test_generateandsendtests(self):
        """Test case for generateandsendtests

        Generate tests if needed and send by email.  # noqa: E501
        """
        pass

    def test_generateandsendtests_0(self):
        """Test case for generateandsendtests_0

        Generate tests if needed and send a reminder.  # noqa: E501
        """
        pass

    def test_getcurrentquestiontest(self):
        """Test case for getcurrentquestiontest

        Validate token and return current question data.  # noqa: E501
        """
        pass

    def test_getmappings(self):
        """Test case for getmappings

        Return a specific mapping instance.  # noqa: E501
        """
        pass

    def test_getmappings_0(self):
        """Test case for getmappings_0

        Return a specific mapping instance with focus on tests.  # noqa: E501
        """
        pass

    def test_getmappingss(self):
        """Test case for getmappingss

        List multiple mappings resources.  # noqa: E501
        """
        pass

    def test_incompatiblemappings(self):
        """Test case for incompatiblemappings

        Send mappings to incompatible in position.  # noqa: E501
        """
        pass

    def test_rejectmapping(self):
        """Test case for rejectmapping

        Reject the applicant.  # noqa: E501
        """
        pass

    def test_rejectmappings(self):
        """Test case for rejectmappings

        Reject the applicant.  # noqa: E501
        """
        pass

    def test_removemappings(self):
        """Test case for removemappings

        Remove mappings from position.  # noqa: E501
        """
        pass

    def test_savecurrentquestiontest(self):
        """Test case for savecurrentquestiontest

        Validate token and save current question answer.  # noqa: E501
        """
        pass

    def test_setignoretestsenrolledmapping(self):
        """Test case for setignoretestsenrolledmapping

        Update the flag to ignore tests on Enrolled stage  # noqa: E501
        """
        pass

    def test_triagemappings(self):
        """Test case for triagemappings

        Triage all applicants by position in progress page  # noqa: E501
        """
        pass

    def test_triagemappings_0(self):
        """Test case for triagemappings_0

        Triage all applicants by position  # noqa: E501
        """
        pass

    def test_undotriagemappings(self):
        """Test case for undotriagemappings

        Send mappings to enrolled stage from position, undo triage.  # noqa: E501
        """
        pass

    def test_updatemappings(self):
        """Test case for updatemappings

        Update a specific mapping instance.  # noqa: E501
        """
        pass

    def test_updatestageorder(self):
        """Test case for updatestageorder

        Update mapping manual order.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
