# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_fields_api import CustomFieldsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomFieldsApi(unittest.TestCase):
    """CustomFieldsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_fields_api.CustomFieldsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_createcustom_fields(self):
        """Test case for createcustom_fields

        Create a new custom-fields  # noqa: E501
        """
        pass

    def test_getcustom_fields(self):
        """Test case for getcustom_fields

        Return a specific custom-field instance.  # noqa: E501
        """
        pass

    def test_getcustom_fields_auto_fill(self):
        """Test case for getcustom_fields_auto_fill

        Return a specific custom-field auto-fill instance.  # noqa: E501
        """
        pass

    def test_getcustom_fieldss(self):
        """Test case for getcustom_fieldss

        List multiple custom-fields resources.  # noqa: E501
        """
        pass

    def test_postcustom_fields_auto_fill(self):
        """Test case for postcustom_fields_auto_fill

        Returns a search of custom-fields auto-fill instances.  # noqa: E501
        """
        pass

    def test_updatecustom_fields(self):
        """Test case for updatecustom_fields

        Update a specific custom-field instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
