# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.companies_api import CompaniesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCompaniesApi(unittest.TestCase):
    """CompaniesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.companies_api.CompaniesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_createcompanies(self):
        """Test case for createcompanies

        Create a new companies  # noqa: E501
        """
        pass

    def test_deletecompanies(self):
        """Test case for deletecompanies

        Delete a specific company instance.  # noqa: E501
        """
        pass

    def test_getcompanies(self):
        """Test case for getcompanies

        Return a specific company instance.  # noqa: E501
        """
        pass

    def test_getcompaniess(self):
        """Test case for getcompaniess

        List multiple companies resources.  # noqa: E501
        """
        pass

    def test_updatecompanies(self):
        """Test case for updatecompanies

        Update a specific company instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
