# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.job_description_templates_api import JobDescriptionTemplatesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestJobDescriptionTemplatesApi(unittest.TestCase):
    """JobDescriptionTemplatesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.job_description_templates_api.JobDescriptionTemplatesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_createjob_description_templates(self):
        """Test case for createjob_description_templates

        Create a new job-description-templates  # noqa: E501
        """
        pass

    def test_deletejob_description_templates(self):
        """Test case for deletejob_description_templates

        Delete a specific job-description-template instance.  # noqa: E501
        """
        pass

    def test_getjob_description_templates(self):
        """Test case for getjob_description_templates

        Return a specific job-description-template instance.  # noqa: E501
        """
        pass

    def test_getjob_description_templatess(self):
        """Test case for getjob_description_templatess

        List multiple job-description-templates resources.  # noqa: E501
        """
        pass

    def test_updatejob_description_templates(self):
        """Test case for updatejob_description_templates

        Update a specific job-description-template instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
