# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.tenants_api import TenantsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestTenantsApi(unittest.TestCase):
    """TenantsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.tenants_api.TenantsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_allowedremovestage(self):
        """Test case for allowedremovestage

        Verify remove tenant's defaultStage.  # noqa: E501
        """
        pass

    def test_beta_features(self):
        """Test case for beta_features

        Returns beta features active in tenant.  # noqa: E501
        """
        pass

    def test_createtenants(self):
        """Test case for createtenants

        Create a new tenants  # noqa: E501
        """
        pass

    def test_getjobsitestenant(self):
        """Test case for getjobsitestenant

        Returns the jobsites for a specific tenant  # noqa: E501
        """
        pass

    def test_gettenants(self):
        """Test case for gettenants

        Return a specific tenant instance.  # noqa: E501
        """
        pass

    def test_gettenantss(self):
        """Test case for gettenantss

        List multiple tenants resources.  # noqa: E501
        """
        pass

    def test_ping_request(self):
        """Test case for ping_request

        Ping request to update user session.  # noqa: E501
        """
        pass

    def test_updatetenants(self):
        """Test case for updatetenants

        Update a specific tenant instance.  # noqa: E501
        """
        pass

    def test_updatetenantsjobsite(self):
        """Test case for updatetenantsjobsite

        Update a specific tenant's jobsite.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
