# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.interview_scripts_api import InterviewScriptsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestInterviewScriptsApi(unittest.TestCase):
    """InterviewScriptsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.interview_scripts_api.InterviewScriptsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_interview_scripts(self):
        """Test case for create_interview_scripts

        Create a new interviewScripts  # noqa: E501
        """
        pass

    def test_deleteinterview_scripts(self):
        """Test case for deleteinterview_scripts

        Delete a specific interviewScript instance.  # noqa: E501
        """
        pass

    def test_getinterview_scripts(self):
        """Test case for getinterview_scripts

        Return a specific interviewScript instance.  # noqa: E501
        """
        pass

    def test_getinterview_scriptss(self):
        """Test case for getinterview_scriptss

        List multiple interviewScripts resources.  # noqa: E501
        """
        pass

    def test_updateinterview_scripts(self):
        """Test case for updateinterview_scripts

        Update a specific interviewScript instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
