# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.screening_questions_api import ScreeningQuestionsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScreeningQuestionsApi(unittest.TestCase):
    """ScreeningQuestionsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.screening_questions_api.ScreeningQuestionsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_screening_questions(self):
        """Test case for create_screening_questions

        Create a new screeningQuestions  # noqa: E501
        """
        pass

    def test_disable_screening_questions(self):
        """Test case for disable_screening_questions

        Disable a specific screeningQuestions  # noqa: E501
        """
        pass

    def test_getscreening_question(self):
        """Test case for getscreening_question

        Return a specific screeningQuestion instance.  # noqa: E501
        """
        pass

    def test_getscreening_questions(self):
        """Test case for getscreening_questions

        List multiple screeningQuestions resources.  # noqa: E501
        """
        pass

    def test_updatescreening_questions(self):
        """Test case for updatescreening_questions

        Update a specific screeningQuestion instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
