# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.screening_test_api import ScreeningTestApi  # noqa: E501
from swagger_client.rest import ApiException


class TestScreeningTestApi(unittest.TestCase):
    """ScreeningTestApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.screening_test_api.ScreeningTestApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_getoriginaltestsforstage(self):
        """Test case for getoriginaltestsforstage

        Returns the original tests for a specific stage  # noqa: E501
        """
        pass

    def test_getscreeningtestposition(self):
        """Test case for getscreeningtestposition

        Returns possible screening test for a specific position and application  # noqa: E501
        """
        pass

    def test_listmindsightfunctions(self):
        """Test case for listmindsightfunctions

        Get Mindsight functions from Mindsight API  # noqa: E501
        """
        pass

    def test_rankdonetest(self):
        """Test case for rankdonetest

        Get Rankdone test from Rankdone API  # noqa: E501
        """
        pass

    def test_rankdonetest_0(self):
        """Test case for rankdonetest_0

        Check Rankdone test from Rankdone API  # noqa: E501
        """
        pass

    def test_rankdonetests(self):
        """Test case for rankdonetests

        Get Rankdone tests from Rankdone API  # noqa: E501
        """
        pass

    def test_testprocessaudio(self):
        """Test case for testprocessaudio

        Upload audio using Google API  # noqa: E501
        """
        pass

    def test_validatetesttokenscreeningtest(self):
        """Test case for validatetesttokenscreeningtest

        Validate token and return if applicant already filled screeningTest.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
