# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.custom_field_groups_api import CustomFieldGroupsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCustomFieldGroupsApi(unittest.TestCase):
    """CustomFieldGroupsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.custom_field_groups_api.CustomFieldGroupsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_createcustom_field_groups(self):
        """Test case for createcustom_field_groups

        Create a new custom-field-groups  # noqa: E501
        """
        pass

    def test_getcustom_field_groups(self):
        """Test case for getcustom_field_groups

        Return a specific custom-field-group instance.  # noqa: E501
        """
        pass

    def test_getcustom_field_groupss(self):
        """Test case for getcustom_field_groupss

        List multiple custom-field-groups resources.  # noqa: E501
        """
        pass

    def test_updatecustom_field_groups(self):
        """Test case for updatecustom_field_groups

        Update a specific custom-field-group instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
