# coding: utf-8

"""
    Kenoby

    Issues or Questions? <a href=\"mailto:devs@kenoby.com\" target=\"_blank\">Send us an e-mail</a>.<br>                      For better experience <a href=\"http://api.kenoby.com/swagger.json\" target=\"_blank\">Download our swagger.json</a>                      and use it on <a href=\"https://www.getpostman.com/\" target=\"_blank\">Postman</a>  # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.dashboards_api import DashboardsApi  # noqa: E501
from swagger_client.rest import ApiException


class TestDashboardsApi(unittest.TestCase):
    """DashboardsApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.dashboards_api.DashboardsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deletedashboards(self):
        """Test case for deletedashboards

        Delete a specific dashboard instance.  # noqa: E501
        """
        pass

    def test_getdashboard(self):
        """Test case for getdashboard

        Return a specific dashboard instance.  # noqa: E501
        """
        pass

    def test_getdashboards(self):
        """Test case for getdashboards

        List multiple dashboards resources.  # noqa: E501
        """
        pass

    def test_updatedashboards(self):
        """Test case for updatedashboards

        Update a specific dashboard instance.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
